### ISSUE TITLE
Search City-Name --> Error 500

### ISSUE THREAD

**Issue by lebalz** [scg-unibe-ch/ese2016-team4#62]
Internal Server Error 500 when City is selected and modified (e.g. "3000 - Bern1")
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at ch.unibe.ese.team4.controller.service.AdService.queryResults(AdService.java:260)
	at ch.unibe.ese.team4.controller.SearchController.results(SearchController.java:62)

**Comment by lebalz** [comment]
no 500er is thrown anymore, but when user enters a city that is not conform to the zip-code, the form will not be posted, but the user has no visual indication, what went wrong.
